consul:
  image: qnib/consul
  ports:
   - "8500:8500"
  environment:
  - DC_NAME=dc1
  dns: 127.0.0.1
  hostname: consul
  privileged: true

heka:
   build: .
   hostname: heka
   dns: 127.0.0.1
   ports:
   - 4352:4352
   environment:
   - FORWARD_TO_HEKA=true
   - DC_NAME=dc1
   links:
   - consul:consul
