[TcpInput]
address = ":55514"
splitter = "newline_splitter"
decoder = "JsonDecoder"

[JsonDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/json.lua"

[newline_splitter]
type = "TokenSplitter"
delimiter = '\n'

[newline_decoder]
type = "ScribbleDecoder"
