[TcpInput]
address = ":55514"
splitter = "newline_splitter"
decoder = "JsonDecoder"

[JsonDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/json.lua"
    [JsonDecoder.config]
    type = "artemis"
    payload_keep = true
    map_fields = true
    Severity = "severity"

[newline_splitter]
type = "TokenSplitter"
delimiter = '\n'

[newline_decoder]
type = "ScribbleDecoder"
