[PayloadEncoder]
append_newlines = true

[RstEncoder]

[LogOutput]
message_matcher = "TRUE"
#message_matcher = "Type == 'heka.statmetric'"
#encoder = "PayloadEncoder"
encoder = "RstEncoder"


[DashboardOutput]
ticker_interval = 5
